### ISSUE TITLE
CrossSimpleAudioPlayer.CreateSimpleAudioPlayer() returns NULL (Android Simulator)

### ISSUE THREAD

**Issue by Sebastian1989101** [adrianstevens/Xamarin-Plugins#17]
It works pretty well on iOS and I released my first app using this today. But now I'm working on the Android port of my app an `CrossSimpleAudioPlayer.CreateSimpleAudioPlayer()` always returns `NULL` instead of an instance.

**Comment by adrianstevens** [comment]
Hi Sebastian,

Can you provide some additional details? What version of Android are you running on the simulator? And double-check you have the nuget package added to your Android head project.

Cheers!

Adrian

**Comment by Sebastian1989101** [comment]
I have this problem on my Galaxy S8 (with Beta Android 8) and on API19 Visual Studio Emulators. All other devices seems to work after a rebuild.

**Comment by adrianstevens** [comment]
Thanks Sebastian - that's really helpful

I'll test this week and hopefully track down the issue

**Comment by Sebastian1989101** [comment]
I'm not 100% sure yet but it looks like the Build process is removing the dependency from the Android project for some build targets.

**Comment by adrianstevens** [comment]
It does sound like the implementation is missing .... I'll add a [Preserve] attribute to the Android assembly. It just means the linker will ignore it (i.e. 100 preserved) but the size is pretty minimal and I think it's safe to assume if someone adds the nuget package they intend to use SimpleAudioPlayer.

**Comment by adrianstevens** [comment]
This _may_ be fixed in the latest version 1.0.2. I'd love to hear feedback.

**Comment by Sebastian1989101** [comment]
Will test it as soon as possible. I just have to push new version to my iOS Beta testers for 3 of my apps until I can get back to the new project.

**Comment by Neverlyn** [comment]
I've been getting this same (or similar) problem recently using 1.0.2.

I seem to be able to get it working again (at least temporarily) buy going to the VS NuGet Package Manager and changing to a different version (1.0.1), rebuilding the solution, then changing back (1.0.2) and rebuilding the solution again. This process worked with an Android 7 emulator.

The above is more of an observation than any kind of solution.

**Comment by thargan** [comment]
When I updated to 8.1 I think I am seeing this - It is acting as if the implementation is missing.

**Comment by adrianstevens** [comment]
I believe this is fixed and there haven't been any further reports - closing issue

**Comment by spencerparkin** [comment]
This bug is still happening in VS 2022 Preview.

**Comment by DavidR5** [comment]
Still experiencing this issue, mine works fine for Android but returns null in Windows. Xam.Plugin.SimpleAudioPlayer 1.6.0 Visual Studio 2022 Preview Version 17.3.0 Preview 1.1
