### ISSUE TITLE
[BUG] [WPF] Plugin.SimpleAudioPlayer.dll not found

### ISSUE THREAD

**Issue by plamen-i** [adrianstevens/Xamarin-Plugins#85]
NuGet installed on a .NET Standard 2.0 project and a .NET Framework WPF project which references .NET Standard 2.0 project.

Target Framework - 4.7.2
Bug in: 1.5.0
Last good version: 1.4.0

Probably caused by: net45 dll in nuget is renamed to Plugin.SimpleAudioPlayer.WPF.dll which probably breaks Bait&Switch to stop working.

**Comment by adrianstevens** [comment]
yes thank you - I'll get this fixed in the next release

**Comment by plamen-i** [comment]
I saw you released 1.6.0 and tested it but the problem still exists. When you will fix this as it keeps me on 1.4.0?
